//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using AssemblyCSharp;
namespace AssemblyCSharp
{
	public class NormalAntibody : Antibody
	{
		public NormalAntibody ()
		{
			base.m_eAntibodyState = AntibodyState.Idle;
			base.m_eAntibodyType = AntibodyType.Normal;
			base.m_sName = "NormalAntibody";
		}

		public NormalAntibody (Vector3 _spawnPoint):base(_spawnPoint)
		{
			base.m_eAntibodyState = AntibodyState.Idle;
			base.m_eAntibodyType = AntibodyType.Normal;
			base.m_sName = "NormalAntibody";
		}

		public override void Start ()
		{
			base.Start ();
			DetermineTargetPoint ();
		}

		public override void DetermineTargetPoint()
		{
			//Determine target point
			base.m_v3TargetPoint = new Vector3 (base.m_v3SpawnPoint.x - (MapManager.s_fCamFocalWidth+MapManager.s_fCamFocalWidth * MapManager.s_fSwitchDistValue)/2, base.m_v3SpawnPoint.y, 0);
		}

		public override void Attack()
		{
		}
	}
}


